# This is a basic workflow to help you get started with Actions
name: PPVland updater

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {} # Enables manual triggering

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: PPVland updater
        run: wget https://iptv-scraper-re.vercel.app/ppvland?timezone=GB -O ppvland.m3u8

      - name: Add file to Git
        run: git add ppvland.m3u8

      - name: Check for changes before commit
        id: changes
        run: |
          if git diff --cached --quiet; then
            echo "no changes"
            echo "changes_detected=false" >> $GITHUB_ENV
          else
            echo "changes_detected=true" >> $GITHUB_ENV
          fi

      - name: Commit changes if any
        if: env.changes_detected == 'true'
        run: |
          git config --local user.email "xxmartinxx1990@gmai.com"
          git config --local user.name "Joansy0404"
          git commit -m "Updated PPVland.m3u8"

      - name: Push changes if commit happened
        if: env.changes_detected == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
