# This is a basic workflow to help you get started with Actions
name: PPVland updater

on:
  
  workflow_dispatch: {} # Enables manual triggering

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download PPVland M3U8
        run: wget https://iptv-scraper-re.vercel.app/ppvland?timezone=gmt -O ppvland.m3u8

      - name: Convert M3U8 to M3U with Headers
        run: |
          # Start the M3U file with the EXTM3U header
          echo '#EXTM3U' > ppvland.m3u
          # Append lines starting with #EXTINF, #EXTVLCOPT, or http
          grep '^#EXTINF\|^#EXTVLCOPT\|^http' ppvland.m3u8 >> ppvland.m3u

      - name: Add M3U file to Git
        run: git add ppvland.m3u # Now adding the M3U file

      - name: Check for changes before commit
        id: changes
        # Check for changes in the M3U file
        run: |
          if git diff --cached --quiet; then
            echo "no changes"
            echo "changes_detected=false" >> $GITHUB_ENV
          else
            echo "changes_detected=true" >> $GITHUB_ENV
          fi

      - name: Commit changes if any
        if: env.changes_detected == 'true'
        run: |
          git config --local user.email "xxmartinxx1990@gmai.com"
          git config --local user.name "Joansy0404"
          # Update commit message
          git commit -m "Updated PPVland.m3u"

      - name: Push changes if commit happened
        if: env.changes_detected == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
