# This is a basic workflow to help you get started with Actions
name: Download File

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch: {} # Enables manual triggering

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download file
        run: wget http://opop.pro/mzQgYQA9VGbS4 -O EchoStream.m3u

      - name: Add file to Git
        run: git add EchoStream.m3u

      - name: Commit changes
        run: |
          git config --local user.email "xxmartinxx1990@gmai.com"
          git config --local user.name "Joansy0404"
          git commit -m "Updated EchoStream.m3u"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
